# Generated by Django 3.0.8 on 2020-09-01 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='음식 이름')),
                ('serving_wt', models.FloatField(verbose_name='제공량')),
                ('kcal', models.FloatField(verbose_name='칼로리')),
                ('carbo', models.FloatField(verbose_name='탄수화물')),
                ('protein', models.FloatField(verbose_name='단백질')),
                ('fat', models.FloatField(verbose_name='지방')),
                ('company', models.TextField(max_length=30, verbose_name='회사명')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='음식 이름')),
                ('serving_wt', models.FloatField(verbose_name='제공량')),
                ('kcal', models.FloatField(verbose_name='칼로리')),
                ('carbo', models.FloatField(verbose_name='탄수화물')),
                ('protein', models.FloatField(verbose_name='단백질')),
                ('fat', models.FloatField(verbose_name='지방')),
                ('company', models.TextField(max_length=30, verbose_name='회사명')),
                ('amount', models.FloatField(default=1, verbose_name='섭취량')),
                ('date', models.DateField(blank=True, default='2020-09-01', verbose_name='날짜')),
                ('authuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodInfo.Table')),
            ],
        ),
    ]
