# Generated by Django 3.0.8 on 2020-08-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodInfo', '0002_auto_20200814_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
