# Generated by Django 3.0.8 on 2020-08-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodInfo', '0005_usertable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='date',
        ),
        migrations.AddField(
            model_name='usertable',
            name='amount',
            field=models.FloatField(default=1, verbose_name='섭취량'),
        ),
    ]
