# Generated by Django 3.0.8 on 2020-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodInfo', '0007_usertable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='date_1',
            field=models.DateField(blank=True, default='2020-08-18', verbose_name='날짜2'),
        ),
    ]
