# Generated by Django 3.0.8 on 2020-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodInfo', '0008_usertable_date_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='date_1',
            field=models.DateField(blank=True, default='2020-08-24', verbose_name='날짜2'),
        ),
    ]
