# Generated by Django 3.0.8 on 2020-09-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 1), ('Female', 0)], max_length=10),
        ),
    ]
